name: hub
version: 2.14.2
release: 1
source:
  - https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz: 74d95fdfb3c78c8af4e2025b04b916ad905ab99a361778500d58269847c7922d
license: MIT
summary: A command-line tool that makes git easier to use with GitHub.
component: network.clients
description: |
  hub is a command line tool that wraps git in order to extend it with extra
  features and commands that make working with GitHub easier.
setup: |
  tar --strip-components 1 -xf $sources/hub-linux-amd64-${version}.tgz
install: |
  mkdir -p $installdir/usr/
  cp -r share $installdir/usr/
  mkdir -p $installdir/usr/share/bash-completion/completions/
  cp -r etc/hub* $installdir/usr/share/bash-completion/completions/
  cp -r bin $installdir/usr/
