name: hub
version    : 2.14.2
release    : 2
source     :
  - git|https://github.com/github/hub.git : v2.14.2
license    : MIT
summary    : A command-line tool that makes git easier to use with GitHub.
component  : system.utils
description: |
  hub is a command line tool that wraps git in order to extend it with extra
  features and commands that make working with GitHub easier.
builddeps  :
  - golang
  - groff
build      : |
  export src_github="src/github.com/github"
  mkdir -p "$src_github"
  export GOPATH=$(pwd)
  ln -sv $(pwd) "$src_github/hub"
  cd "$src_github/hub"
  export prefix=$installdir/usr
  %make install
